CREATE DATABASE `server`;
CREATE TABLE `server`.`users` (
  `uuid` VARCHAR(36) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `modified_at` DATETIME NOT NULL,
  `hash` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`uuid`)
);
CREATE TABLE `server`.`sw_people` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `birth_year` VARCHAR(16) NOT NULL,
  `eye_color` VARCHAR(16) NOT NULL,
  `gender` VARCHAR(16) NOT NULL,
  `hair_color` VARCHAR(16) NOT NULL,
  `height` VARCHAR(8) NOT NULL,
  `mass` VARCHAR(8) NOT NULL,
  `skin_color` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`)
);
CREATE TABLE `server`.`weather` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `longitude` FLOAT NOT NULL,
  `latitude` FLOAT NOT NULL,
  `weather_info` VARCHAR(32) NOT NULL,
  `weather_description` VARCHAR(64) NOT NULL,
  `weather_icon` VARCHAR(16) NOT NULL,
  `temperature` FLOAT NOT NULL,
  `feels_like` FLOAT NOT NULL,
  `temp_min` FLOAT NOT NULL,
  `temp_max` FLOAT NOT NULL,
  `pressure` INT NOT NULL,
  `humidity` INT NOT NULL,
  `sea_level` INT NULL,
  `grnd_level` INT NULL,
  `visibility` INT NOT NULL,
  `wind_speed` FLOAT NOT NULL,
  `wind_direction` INT NOT NULL,
  `wind_gust` FLOAT NULL,
  `clouds_all` INT NOT NULL,
  `rain_volume_1h` FLOAT NULL,
  `rain_volume_3h` FLOAT NULL,
  `snow_volume_1h` FLOAT NULL,
  `snow_volume_3h` FLOAT NULL,
  `data_calculation_time` DATETIME NOT NULL,
  `country` VARCHAR(32) NOT NULL,
  `sunrise` DATETIME NOT NULL,
  `sunset` DATETIME NOT NULL,
  `timezone` INT NOT NULL,
  `city_id` INT NOT NULL,
  `city_name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`)
);